### DISCUSSION TITLE
No events found - OpenSearch / Filebeat

### DISCUSSION THREAD

**Discussion by opoplawski** [jasonish/evebox#219] [General]
We are shipping suricata events from filebeat -> logstash -> opensearch and preserving the filebeat-* index.  I think I've configured everything properly:
```
database:
  type: elasticsearch
  elasticsearch:
    url: https://FQDN:9200
    index: filebeat
    disable-certificate-check: true
    keyword: ""
    username: logstash
    password: XXX
```
```
EVEBOX_OPTS="--host 0.0.0.0 --ecs -v -v"
```

I'm not seeing any errors/warnings on evebox or opensearch.  How can I see what queries are being made?
