### ISSUE TITLE
Rule and PAYLOAD DISPLAY ON EVEBOX 

### ISSUE THREAD

**Issue by mounaBoo** [jasonish/evebox#106]
Hello , 

I have recently installed evebox with elasticsearch and logstash, I want to know how to add rule and payload display on evebox dashboad like it's showing in demo :
https://demo.evebox.org/#/event/01DAMA2YVTHMDSDS1TNSWB2XN0;referer=%2Finbox

**Comment by jasonish** [comment]
In your suricata.yaml you will want to enable payload and rule logging.  So you'll want to update your outputs.eve-log to look something like:
```
outputs:
  eve-log:
    types:
      - alert:
        payload: yes
        metadata:
          rule:
            metadata: true
            raw: true
```
This should add the rule and the payload to the eve record generated by Suricata.  Then EveBox can show it.
