### ISSUE TITLE
Link to ET missing

### ISSUE THREAD

**Issue by filippocarletti** [jasonish/evebox#109]
The link to the ET signature in the top right of an alert page is now a number (a counter) that links back to the inbox. Refreshing the page the number becomes an external link to doc.emergingthreats.net.

# Steps to reproduce

1. Click on an alert in the inbox page
2. See the top right: it shows the number of rule hits
3. Refresh the page (hit F5), the number becomes the link to the ET signature

EveBox 0.10.2.

First click on the alert from inbox:
![Screenshot from 2019-05-15 11-47-01](https://user-images.githubusercontent.com/106798/57766248-52415300-7707-11e9-8a1c-1a6a82028c23.png)

After page refresh:

![Screenshot from 2019-05-15 11-47-15](https://user-images.githubusercontent.com/106798/57766194-3b026580-7707-11e9-9efc-6f1aefa8e372.png)

**Comment by jasonish** [comment]
The ET link is not provided by EveBox itself, but some integration.  Are you running EveBox on SELKS?

**Comment by filippocarletti** [comment]
No SELKS, it's EveBox fed by eve.json using sqlite.

**Comment by jasonish** [comment]
Can you provide your evebox.yaml? Maybe there is an event service defined in there for ET links.

**Comment by filippocarletti** [comment]
```
data-directory: /var/lib/evebox

http:
  tls:
    enabled: false
  reverse-proxy: true

database:
  type: sqlite
  retention-period: 30

authentication:
  required: no

input:
  enabled: true
  filename: "/var/log/suricata/eve.json"

geoip:
  disabled: false

event-services:

  - type: custom
    enabled: true
    name: ET
    url: http://doc.emergingthreats.net/{{alert.signature_id}}
```
