### ISSUE TITLE
custom-fields not visible in events

### ISSUE THREAD

**Issue by majst01** [jasonish/evebox#137]
Hi,

first of all, thanks for this great piece of  software ! Thanks 

I setup a two fold scenario with one host running suricata and the evebox-agent which forwards to evebox-server, the server has sqlite configured as database backend.

The agent.yaml looks like:
```yaml
 server:
      url: http://evebox-server-service:80
     bookmark-directory: "/var/lib/evebox"
 input:
      filename: "/var/log/suricata/eve.json"
    custom-fields:
      host: "evebox-agent"
      clusterid: "firewall-controller-test"
      projectid: "development"
 rules:
      - /etc/suricata/rules/*.rules
```

The events arrive at the evebox-server and are visible, but i am unable to see the custom fields anywhere.
I expected them to be added to the event payload json but i am probably wrong.

What am i missing ?

any help appreciated

**Comment by jasonish** [comment]
Which version are you using? Made some very large internal changes and may have broke something recently.

**Comment by majst01** [comment]
I used jasonish/evebox:latest and jasonish/evebox:master, with both same result

**Comment by jasonish** [comment]
I am unable to replicate this with those 2 docker images.

First, you'll only see these custom fields in the raw JSON output at the bottom of the event page.  This isn't ideal. To make them more viewable, I'd need to nest them under some other object which I could then display near the top.  But they are still usable for searching..  ie: "projectid:development" in the search bar.

If you are not seeing them in the raw JSON, can you verify the formatting of your YAML file? Some of the indentation in the cut and paste looks a little off. It should look more like:
```
server:
  url: http://10.16.1.10:5636
input:
  filename: "/var/log/suricata/eve.json"
  custom-fields:
    host: "evebox-agent"
    clusterid: "firewall-controller-test"
    projectid: "development"
```
