### ISSUE TITLE
Elasticsearch response has no aggregations

### ISSUE THREAD

**Issue by kmz161** [jasonish/evebox#155]
I using docker-compose for deploying elasticsearch and evebox
```
version: "2"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  evebox:
    image: jasonish/evebox:latest
    volumes:
      - log:/var/log/sagan:z
    links:
      - elasticsearch
    ports:
      - 5636:5636
    command:  -e http://localhost:9200

volumes:
    log:
    elasticsearch-data:
```
And I using filebeat for sending Sagan log to elasticsearch
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/sagan/eve.json

  json.keys_under_root: true
  overwrite_keys: true


setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: [localhost:9200]
```
Elasticsearch contains data but evebox has error
```WARN evebox::elastic::eventstore: Elasticsearch response has no aggregations```
What do I need for working evebox?
