### ISSUE TITLE
Read from custom ES index

### ISSUE THREAD

**Issue by peter2141** [jasonish/evebox#159]
Hello. I wanted to ask if it is any option to read from specified elasticsearch index? I ship suricata logs to elasticsearch using filebeat (not using the filebeat module, but setting it up in `filebeat.yml`). If I specify the option `-i filebeat` then Evebox won't read from the indices created by filebeat (format is `filebeat-7.11.2-YY.mm.dd`), but it will create a new index in format `filebeat-YY.mm.dd`. Is there any solution for this? I want to rotate my indices hourly using elastic index lifecycle management, which is applied on indices created by filebeat. Thank you.

**Comment by peter2141** [comment]
I ran it with this command:  `evebox server  -e http://localhost:9200 --host 0.0.0.0 -i filebeat`, is it ok?

**Comment by jasonish** [comment]
Can you share your filebeat configuration? Is it using `json.keys_under_root: true`?

**Comment by peter2141** [comment]
Yes it is using. Here is my `filebeat.yaml`.

```
filebeat.inputs:
- type: log  
  enabled: true
  paths:
    - /var/log/suricata/eve.json
  json.keys_under_root: true
  overwrite_keys: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  
setup.dashboards.enabled: false
  
output.elasticsearch:  
  hosts: ["http://localhost:9200"]
    
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

```

One more question, is the option database.elasticsearch.index in `evebox.yaml` the same setting as specifiing the option `-i`? When I set the index name to filebeat in `evebox.yaml` then after start it creates other index, see the screenshot below. I have the option input.enabled set to `false`.

![obrázok](https://user-images.githubusercontent.com/22367448/111658915-1567ab00-880d-11eb-8bdc-27388b225f72.png)
