### ISSUE TITLE
Connect to a secured Elastic node

### ISSUE THREAD

**Issue by ngms17** [jasonish/evebox#165]
Hi.

Evebox is the showing the following error:

2021-04-07 11:36:44 ERROR evebox::server::main: Failed to get Elasticsearch version, things may not work right: error=missing authentication credentials for REST request [/]

Maybe because I have a secured ELK stack. My Suricata and ELK are running on different machines. Evebox is installed on the ELK machine. How can I configure Evebox to consume the filebeat index that I have on Elastic?

Thanks

**Comment by jasonish** [comment]
You'll have to create a configuration parameter to provide a username and password..  A minimal configuration file might look like:
```
database:
  elasticsearch:
    username: my-username
    password: my-password
```
